### ISSUE TITLE
Not compatible with Refined Storage Addons

### ISSUE THREAD

**Issue by embeddedt** [tth05/morerefinedstorage#15]
#### Issue description:

It crashes when used with Refined Storage Addons because some APIs have changed.

#### Steps to reproduce:

Install the latest versions of Refined Storage Addons and More Refined Storage.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- Refined Storage: 2.2.1

I haven't tested on a server.

#### If a (crash)log is relevant for this issue, link it here:

This is the first message you get upon trying to load a world:

```
java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorage/apiimpl/util/OneSixMigrationHelper
	at com.raoulvdberge.refinedstorageaddons.proxy.ProxyCommon.fixBlockMappings(ProxyCommon.java:37) ~[ProxyCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1580_ProxyCommon_fixBlockMappings_MissingMappings.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:684) ~[GameData.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_201]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_201]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_201]
```

I rebuilt the addons locally to remove references to `OneSixMigrationHelper`, which then fails because of API changes to `onCrafted`, `onCraftedShift`, etc.

Is there an alternative version of the addons I should be using?

**Comment by tth05** [comment]
The RS Addons mod is not required anymore. The Wireless Crafting Grid is built into More Refined Storage already.
Forgot to state it in the README, my bad.

**Comment by embeddedt** [comment]
Sorry; I should have checked the code more closely before opening this issue. Glad to hear that! Looking forward to the performance improvements.

**Comment by Pelotrio** [comment]
You will not be disappointed.

**Comment by bigenergy** [comment]
@tth05 
[offtop] _do you have a discord profile? i want to contact you_

**Comment by tth05** [comment]
@bigenergy Bagga#3886
